# Generated by Django 6.0.2 on 2026-02-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_Name', models.CharField(max_length=254)),
                ('Emp_Email', models.EmailField()),
                ('Emp_Mobile', models.IntegerField()),
            ],
        ),
    ]
