# Generated by Django 6.0.2 on 2026-02-20 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeee',
            name='Emp_Name',
            field=models.CharField(max_length=100),
        ),
    ]
