# Generated by Django 6.0.2 on 2026-02-20 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_employeee_emp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeee',
            old_name='Emp_Name',
            new_name='Emp_name',
        ),
    ]
