# Generated by Django 6.0.2 on 2026-02-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_rename_emp_name_employeee_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField()),
                ('U_pass', models.CharField()),
                ('u_mail', models.EmailField(max_length=254)),
                ('u_mob', models.IntegerField()),
            ],
        ),
    ]
