# Generated by Django 6.0.2 on 2026-02-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='u_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
