# Generated by Django 6.0.2 on 2026-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_user_u_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employeee',
        ),
    ]
