# Generated by Django 6.0.2 on 2026-02-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_delete_employeee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employeee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=100)),
                ('Emp_Email', models.EmailField(max_length=254)),
                ('Emp_Mobile', models.IntegerField()),
            ],
        ),
    ]
