# Generated by Django 6.0.2 on 2026-02-26 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_employeee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employeee',
            new_name='Employee',
        ),
    ]
