# Generated by Django 6.0.2 on 2026-03-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_rename_employeee_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdate', models.CharField(max_length=11)),
                ('btime', models.CharField(max_length=11)),
                ('bimage', models.ImageField(upload_to='image')),
            ],
        ),
        migrations.RenameModel(
            old_name='user',
            new_name='User1',
        ),
    ]
