# Generated by Django 6.0.2 on 2026-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_blog_rename_user_user1'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='btext',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
